
# html lang
language: en

# Default display mode (设置网站默认显示模式)
# light (default) / dark
display_mode: light

# dns-prefetch preconnect
preconnect:
  # - https://unpkg.com/
  # - https://cdn.jsdelivr.net/

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# Website Background
background:
  url: /

############################### Navigation Bar ############################### > start
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
nav:
  logo: /favicon.ico #logo 图片的链接路径
  display_title: true #显示站点名称，默认为 true, 设置 false 为不显示

# main menu navigation
# 使用图标，请在链接后面 || 增加，示例：# Home: / || fas fa-home
# 下拉菜单请在列表顶里增加，示例：# List||fas fa-list:
menu:
  Home: / || fas fa-home
  List||fas fa-list:
    Item1: /
    Item2: /
  Link: link/ || fas fa-link
  About: about/ || fas fa-heart

# 导航菜单的按钮设置
nav_button:
  enable: true #导航栏右侧按钮总开关，设置 false 为不显示，以下所有按钮开启了也不会显示
  container:
    enable: true #在导航栏显示内容按钮，设置 false 为不显示
    title: Try for free
    url: /
  search: #TOTO: 待完成，此功能暂时还没做好
    enable: false #在导航栏显示搜索按钮，设置 false 为不显示
    title: Search...
    icon: #搜索的图标，如果不设置，则使用自带的 svg 样式
############################### Navigation Bar ############################### > end

############################### Banner ############################### > start
banner:
  enable: true #首页轮播图，设置 false 为不显示
  css: css/swiper.min.css #swiper css
  js: js/swiper.min.js #swiper js
  control: js/swiper-banner-control.js #配置 swiper 的声明文件
  button_style: solid #按钮的样式风格: solid
  wrapper:
    # #轮播图设置参数介绍
    # - img: /img.jpg #电脑端显示的图片
    #   mobile_img: https://github.com/mobile-img.jpg #手机端显示的图片，理应为移动端配图，不然会以电脑端的图片显示
    #   introduce: #图片介绍的信息组，这个值不用填写
    #     position: center #介绍信息所在位置: left (PC左边，移动端显示为上面), center (居中), right (PC右边，移动端显示为下面). 不设置则只显示图片、不显示介绍
    #     title: Getting #介绍主标题
    #     subtitle: Wit once bought is worth twice taught #介绍的副标题内容
    #     white_title: false #标题的字体颜色是否为白色, false 为黑色, true 为白色
    #     button_title: Read more > #介绍按钮的标题，同按钮链接一样，为空则不显示按钮，按钮样式请在 button_style 里修改
    #     button_url: / #介绍按钮的链接，同按钮标题一样，为空则不显示按钮
    #第一个轮播图
    - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/003.webp
      mobile_img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/014.webp
      introduce:
        position: center
        title: Getting
        subtitle: Wit once bought is worth twice taught
        white_title: false
        button_title: Read more >
        button_url: /
    #第二个轮播图
    - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/005.webp
      mobile_img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/011.webp
      introduce:
        position: left
        title: 阿甘正传
        subtitle: 生活就像一盒巧克力，你永远不知道下一个是什么
        white_title: false
        button_title: 点击查看 >
        button_url: /
    #第三个轮播图
    - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/002.webp
      mobile_img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/012.webp
      introduce:
        position: right
        title: Actions
        subtitle: To learn to be just and constant, not just is sui Hui, not constant retreat
        white_title: true
        button_title: Read more >
        button_url: /
#如需要更多轮播图请自行复制上面的配置格式，注意缩进层次关系。
############################### Banner ############################### > end

############################### Components ############################### > start
components:
  # 这里的组件只会显示在首页，按 for_home 里填写的组件名先后排序
  for_home: [slogans, cards, video] # 每个以英文的逗号分开
  # 组件库
  library:
    # ----------------------------------- Library: Slogans ----------------------------------- > start
    # 网站的核心标语信息组件
    slogans:
      badge: declaration #标语的徽标，为空不显示
      title:
        - Light tomorrow with today.
        - Time is that we do not come loose.
        # - 这是没有显示出来的第三行标题，支持多行标题，不建议超过三行
      subtitle:
        - A friend is one of the nicest things you can have, and one of the best things you can be.
        - Friendship is a sheltering tree.
        # - 这是没有显示出来的第三行内容文本，支持多行文本，不宜过多
      button_style: solid #按钮的样式风格: solid
      button_title: Learn more > #介绍按钮的标题，同按钮链接一样，为空则不显示按钮
      button_url: / #介绍按钮的链接，同按钮标题一样，为空则不显示按钮
    # ----------------------------------- Library: Slogans ----------------------------------- > end

    # ----------------------------------- Library: Cards ----------------------------------- > start
    cards:
      badge: strength #卡片的徽标，为空不显示
      item:
        # #cards组件的各卡片参数设置，建议 3-4 个卡片为佳，5 个以上会不显示
        # - img: #卡片的背景图
        #   category: #此内容的归类
        #   title: #标题
        #   link_text: 进一步了解 > #链接显示的文本
        #   link_url: # 链接地址
        - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/003.webp
          category: 测试测试
          title: 如何打造出一个优雅的示例
          link_text: 进一步了解 >
          link_url: /
        - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/005.webp
          category: test text
          title: Time is that we do not come loose.
          link_text: Read more >
          link_url: /
        - img: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/002.webp
          category: 还是测试
          title: 生活就像一盒巧克力，你永远不知道下一个是什么
          link_text: 点击查看 >
          link_url: /
    # ----------------------------------- Library: Cards ----------------------------------- > end

    # ----------------------------------- Library: Video ----------------------------------- > start
    video:
      poster: https://unpkg.com/volantis-static@0.0.1660614606622/media/wallpaper/minimalist/2020/003.webp #视频的封面图片
      url: https://github.com/volantis-x/volantis-docs/releases/download/assets/IMG_0341.mov #视频地址
      title: Xaoxuu's cat
      info_item:
        - title: Elegant figure
          text: elegant figure, very flexible
        - title: Explosive force
          text: small body with incredible energy
        - title: Have fun
          text: keep a happy heart very good
      button_style: solid #按钮的样式风格: solid
      button_title: Learn more > #介绍按钮的标题，同按钮链接一样，为空则不显示按钮
      button_url: / #介绍按钮的链接，同按钮标题一样，为空则不显示按钮
    # ----------------------------------- Library: Video ----------------------------------- > end
############################### Components ############################### > end