
# html lang
language: en

# main menu navigation
# 使用图标，请在链接后面 || 增加，示例：# Home: / || fas fa-home
# 下拉菜单请在列表顶里增加，示例：# List||fas fa-list:
menu:
  # Home: / || fas fa-home
  # List||fas fa-list:
  #   Item1: /
  #   Item2: /
  # About: /about
  # Link: /link/ || fas fa-link
  # About: /about/ || fas fa-heart

# Default display mode (设置网站默认显示模式)
# light (default) / dark
display_mode: light

# dns-prefetch preconnect
preconnect:
  # - https://unpkg.com/
  # - https://cdn.jsdelivr.net/

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    # - <link rel="stylesheet" href="/xxx.css">
  bottom:
    # - <script src="xxxx"></script>

# Website Background
background:

nav:
  logo:
  display_title: true